# Generated by Django 5.1 on 2024-12-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packApp2', '0003_pack_promocion_nombre_boleto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack_promocion',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='boleto',
        ),
    ]
