# Generated by Django 5.1 on 2024-12-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packApp2', '0004_alter_pack_promocion_id_delete_boleto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack_promocion',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
