# Generated by Django 5.1 on 2024-12-05 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packApp2', '0005_alter_pack_promocion_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
