# Generated by Django 5.1 on 2024-11-19 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packApp2', '0003_pack_promocion_nombre_boleto'),
        ('vueloApp', '0003_alter_boleto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletos', to='packApp2.pack_promocion'),
        ),
    ]
